# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-09 18:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[(b'cs', b'Computer Science & Engineering'), (b'ec', b'Electronics & Communication Engineering'), (b'eee', b'Electrical & Electronics Engineering'), (b'is', b'Information Science & Engineering'), (b'mech', b'Mechanical Engineering'), (b'mba', b'Management Studies - MBA')], max_length=100, verbose_name=b'Branch')),
                ('year', models.CharField(choices=[(b'1', b'1st'), (b'2', b'2nd'), (b'3', b'3rd'), (b'4', b'4th')], max_length=5, verbose_name=b'Year')),
                ('preferred_medium', models.CharField(choices=[(b'books', b'Books'), (b'blogs', b'Blogs'), (b'images', b'Images'), (b'videos', b'Videos'), (b'others', b'Others')], max_length=100, verbose_name=b'Preferred Medium')),
                ('preferred_language', models.CharField(choices=[(b'eng', b'English'), (b'kan', b'Kannada'), (b'hin', b'Hindi'), (b'othr', b'Others')], max_length=100, verbose_name=b'Preferred Language')),
                ('interests', models.CharField(choices=[(b'ai/ml', b'AI/ML'), (b'iot', b'IoT'), (b'cyber security', b'Cyber Security'), (b'machine drawing', b'Machine Drawing'), (b'autonomous vehicles', b'Autonomous Vehicles'), (b'others', b'Others')], max_length=100, verbose_name=b'Your Interests')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
