# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-23 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form_6', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='branch',
            field=models.CharField(choices=[(b'cs', b'Computer Science Engineering'), (b'ec', b'Electronics & Communication Engineering'), (b'eee', b'Electrical & Electronics Engineering'), (b'is', b'Information Science Engineering'), (b'mech', b'Mechanical Engineering'), (b'mba', b'Management Studies - MBA')], max_length=100, verbose_name=b'Branch'),
        ),
    ]
