# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-10 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form_6', '0002_auto_20200923_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='branch',
            field=models.CharField(choices=[(b'cs', b'Computer Science Engineering'), (b'ec', b'Electronics & Communication Engineering'), (b'eee', b'Electrical & Electronics Engineering'), (b'is', b'Information Science Engineering'), (b'mech', b'Mechanical Engineering'), (b'mba', b'Management Studies - MBA')], max_length=100, verbose_name=b'Department'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='interests',
            field=models.CharField(choices=[(b'ai/ml', b'AI/ML'), (b'iot', b'IoT'), (b'cyber security', b'Cyber Security'), (b'cloud computing', b'Cloud Computing'), (b'robotics', b'Robotics'), (b'3d printing', b'3D Printing'), (b'machine drawing', b'Machine Drawing'), (b'autonomous vehicles', b'Autonomous Vehicles'), (b'entrepreneurship', b'Entrepreneurship'), (b'others', b'Others')], max_length=100, verbose_name=b'Your Interest'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='preferred_language',
            field=models.CharField(choices=[(b'eng', b'English'), (b'kan', b'Kannada'), (b'hin', b'Hindi'), (b'othr', b'Others')], max_length=100, verbose_name=b'Preferred Medium of Language'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='preferred_medium',
            field=models.CharField(choices=[(b'books', b'Books'), (b'blogs', b'Blogs'), (b'articles', b'Articles'), (b'journals', b'Journals'), (b'images', b'Images'), (b'videos', b'Videos'), (b'others', b'Others')], max_length=100, verbose_name=b'Preferred Medium of Learning'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='year',
            field=models.CharField(choices=[(b'1', b'1st year'), (b'2', b'2nd year'), (b'3', b'3rd year'), (b'4', b'4th year')], max_length=5, verbose_name=b'Year of Study'),
        ),
    ]
