# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-09 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='branch',
            field=models.CharField(max_length=100, verbose_name=b'Branch'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='enrollment_year',
            field=models.CharField(choices=[(b'1', b'1st'), (b'2', b'2nd'), (b'3', b'3rd'), (b'4', b'4th')], max_length=5, verbose_name=b'Enrollment Year'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='interests',
            field=models.CharField(choices=[(b'coding', b'Coding'), (b'reading', b'Reading'), (b'sports', b'Sports'), (b'music', b'Music'), (b'dance', b'Dance'), (b'data science', b'Data Science'), (b'ai/ml', b'AI/ML'), (b'iot', b'IoT'), (b'cyber security', b'Cyber Security'), (b'video development', b'Video Development'), (b'databases', b'Databases'), (b'python', b'Python'), (b'java', b'Java'), (b'open source', b'Open Source'), (b'others', b'Others')], max_length=100, verbose_name=b'Your Interests'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='preferred_language',
            field=models.CharField(max_length=100, verbose_name=b'Preferred Language'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='preferred_multimedia',
            field=models.CharField(max_length=100, verbose_name=b'Preferred Multimedia'),
        ),
    ]
